name: 🚀 Epic Product
description: Very general information regarding a potential product that would advance a milestone and be an output after completing it.
title: "[EPIC]: <insert product name>"
labels: ["Type: EPIC"]
body:
  - type: markdown
    attributes:
      value: |
        This is meant to create a loosely structured space to jot down some ideas/deliverables for a project that you would like the team to work on to advance a milestone.
  - type: input
    id: creater-name
    attributes:
      label: Requestor Name
      description: Any and all projects deserve some credit so let us know who thought of it! 😊
      placeholder: ex, FirstName LastName
    validations:
      required: true
  - type: dropdown
    id: milestone
    attributes:
      label: Milestone Selection
      description: What milestone will this product help advance or be an output from?
      multiple: false
      options:
        - M1 - Establish a governance Secretariat
        - M2 - Publish whitepaper / position paper
        - M3 - Engage Digital ID Lab and Digital Governance Council
        - M4 - Develop a Cloud Adoption Framework
        - M5 - Deploy an interoperability (API) platform
        - M6 - Define a technology engagement framework
        - M7 - Implementation of an identity-based (Zero-Trust) security model
        - M8 - Deploy PBMM-ready Cloud Infrastructure for Public Health Intelligence (CIPHI)
        - M9 - Deliver data mesh recommendations
        - M10 - Provide PHAC-designed production-ready data analytics capabilities
        - N/A
  - type: input
    id: problem-statement
    attributes:
      label: Problem Statement
      description: In ONE LINE, what is the issue/question that this product is aiming to solve?
      placeholder: Insert problem statement here.
    validations:
      required: true
  - type: input
    id: desired-outcome-summary
    attributes:
      label: Desired Outcome Summary
      description: In ONE LINE, what are you expecting/hoping that the outcome of this product will be?
      placeholder: Insert value proposition here.
    validations:
      required: true
  - type: textarea
    id: detailed-description
    attributes:
      label: Detailed Description
      description: Please provide some more detail to the description of the product.
      placeholder: Longer description here.
      value: "Lets get some more details!"
    validations:
      required: true
  - type: textarea
    id: proposed-features
    attributes:
      label: Detailed Description
      description: What are some basic functions that this product will need?
      placeholder: Create a list of checkboxes; - [ ] Some text here
      value: |
        Create a checklist of proposed features/functions using the following format
        - [ ] <insert basic function here>
    validations:
      required: true
  - type: input
    id: business-intake-dependencies
    attributes:
      label: Dependencies
      description: Is there an issue that needs to be completed before this can start?
      placeholder: Inset the issue number; /#<number>, where number is in the URL of the issue as in github.com/PHACDataHub/project-intake/issues/<number>
    validations:
      required: false
